spring.application.name=finance-dashboard-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres
spring.datasource.password=Sourav@2005

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.prefix=/api/v1
auth.token.jwtSecret=VGhpc0lzQVNlY3VyZUpXVFNlY3JldEtleUZvckhTMjU2QXV0aGVudGljYXRpb24=
auth.token.expirationInMils=3600000
